## **Name: Samarth Burkul**  
## **Roll No.: 24102C2004**

## R Programming NPTEL Week 9

In [ ]:
print("The zero occurs at"); print(2*pi); print("radians")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"

In [ ]:
cat("The zero occurs at", 2*pi, "radians")

The zero occurs at 6.283185 radians

In [ ]:
d=date()
cat("Today's date is:", d, "\n")

Today's date is: Mon Sep 21 08:37:50 2026

In [ ]:
x=1:10
x
cat(x,sep=" ++ ")
cat("\n")
cat(x,sep=" / ")

 [1]  1  2  3  4  5  6  7  8  9 10

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10
1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

In [ ]:
x=7
cat("sqaure of", x, "is", x^2, "!\n")

sqaure of 7 is 49 !

In [ ]:
cat("the square root of", x, "is approximately", format(sqrt(x), digits = 3), "\n")

the square root of 7 is approximately 2.65

In [ ]:
evenno=c(2,4,6,8,10)
evenno
cat("The first few even nos are: ", evenno, "..\n")

[1]  2  4  6  8 10

The first few even nos are:  2 4 6 8 10 ..

In [ ]:
x=1:10
x
cat(x, fill=2, labels=paste("(",letters[1:10],"):"))

 [1]  1  2  3  4  5  6  7  8  9 10

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

In [ ]:
paste(1:12)
as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [ ]:
paste("Everybody", "loves", "R Programming.")
paste("Everybody", "loves", "R Programming.", sep="*")
paste("Everybody", "loves", "R Programming.", sep="===")

[1] "Everybody loves R Programming."

[1] "Everybody*loves*R Programming."

[1] "Everybody===loves===R Programming."

In [ ]:
names = c("Prof. Singh", "Mr. Venkat", "Dr. Jha")
names
paste(names, "is", "a good", "person")

[1] "Prof. Singh" "Mr. Venkat"  "Dr. Jha"

[1] "Prof. Singh is a good person" "Mr. Venkat is a good person"
[3] "Dr. Jha is a good person"

In [ ]:
paste(1, "is first", 2, "is second", 3, "is third", sep="#")
paste(1, "is first         ", 2, "is second         ", 3, "is third       ", sep="#")

[1] "1#is first#2#is second#3#is third"

[1] "1#is first         #2#is second         #3#is third       "

In [ ]:
x=paste("Ex", 1:5, SEP="_")

In [ ]:
x

[1] "Ex 1 _" "Ex 2 _" "Ex 3 _" "Ex 4 _" "Ex 5 _"

In [ ]:
x=paste("Ex", 1:5, sep="_", collapse="")
x

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [ ]:
paste0(1:10)
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [ ]:
x="The&!syntax&!of&!paste&!is!&available! &inthe online-help"
x

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

In [ ]:
strsplit(x, split="!")

[[1]]
[1] "The&"                "syntax&"             "of&"
[4] "paste&"              "is"                  "&available"
[7] " &inthe online-help"

In [ ]:
strsplit(x, split="&!")

[[1]]
[1] "The"                               "syntax"
[3] "of"                                "paste"
[5] "is!&available! &inthe online-help"

In [ ]:
y=strsplit(x,split="!&")
y[[1]][1]

[1] "The&!syntax&!of&!paste&!is"

In [ ]:
dates=c("2020-07-24", "2021-08-25","2022-09-26","2023-10-27")
datesplt=strsplit(dates, "-")
datesplt

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "09"   "26"

[[4]]
[1] "2023" "10"   "27"

In [ ]:
datemat=matrix(unlist(datesplt), nrow=4,ncol=3, byrow=TRUE)
datemat

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 09   26
[4,] 2023 10   27

In [ ]:
datematrix=matrix(as.numeric(unlist(datesplt)),nrow=4,ncol=3,byrow=TRUE)
datematrix

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

In [ ]:
strsplit("Shalabh", split="")

[[1]]
[1] "S" "h" "a" "l" "a" "b" "h"

In [ ]:
nchar(x, type="chars", allowNA=FALSE,keepNA = NA)
nzchar(x,keepNA = FALSE)

[1] 57

[1] TRUE

In [ ]:
x="R course 24.07.2022"
y="Number of participants: 25"
nchar(x)
nchar(y)

[1] 19

[1] 26

In [ ]:
nzchar(x)
nzchar(y)

[1] TRUE

[1] TRUE

In [ ]:
y=c("Apple", "", "Cake")
nchar(y)
nzchar(y)

[1] 5 0 4

[1]  TRUE FALSE  TRUE

In [ ]:
z1=c(1.1,2.22,5.55)
nchar(z1)

[1] 3 4 4

In [ ]:
toupper(x)
tolower(x)

[1] "R COURSE 24.07.2022"

[1] "r course 24.07.2022"